- hosts: all
  remote_user: user
  become: true
  tasks:

    - name: Install the Apache web server
      apt:
        name: apache2
        state: present

    - name: enabling apache service
      service:
        name: apache2
        enabled: true
        state: started

    - name: installing mysql-server
      apt:
        name: mysql-server
        state: present

    - name: enabling mysql service
      service:
        name: mysql
        enabled: true
        state: started

    - name: installing php and its modules
      apt:
        name:
          - php
          - libapache2-mod-php
          - php-mysql
        state: present
